# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "gtksourceview" ]
  pull_request:
    branches: [ "gtksourceview" ]

jobs:

  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install depends
      run: ./install-depends.sh

    - name: Build
      run: ./maketar.sh

    - name: Upload my-artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./gnote*.tgz